/**
 * LaTeX math command tables.
 *
 * Maps LaTeX command names to Unicode characters and MathML element types.
 */

export interface SymbolDef {
  /** Unicode character(s) */
  char: string;
  /** MathML element type */
  element: 'mi' | 'mo';
}

/** LaTeX command → Unicode symbol mapping. */
export const symbols: Record<string, SymbolDef> = {
  // Greek lowercase
  alpha:      { char: '\u03B1', element: 'mi' },
  beta:       { char: '\u03B2', element: 'mi' },
  gamma:      { char: '\u03B3', element: 'mi' },
  delta:      { char: '\u03B4', element: 'mi' },
  epsilon:    { char: '\u03F5', element: 'mi' },
  varepsilon: { char: '\u03B5', element: 'mi' },
  zeta:       { char: '\u03B6', element: 'mi' },
  eta:        { char: '\u03B7', element: 'mi' },
  theta:      { char: '\u03B8', element: 'mi' },
  vartheta:   { char: '\u03D1', element: 'mi' },
  iota:       { char: '\u03B9', element: 'mi' },
  kappa:      { char: '\u03BA', element: 'mi' },
  lambda:     { char: '\u03BB', element: 'mi' },
  mu:         { char: '\u03BC', element: 'mi' },
  nu:         { char: '\u03BD', element: 'mi' },
  xi:         { char: '\u03BE', element: 'mi' },
  pi:         { char: '\u03C0', element: 'mi' },
  varpi:      { char: '\u03D6', element: 'mi' },
  rho:        { char: '\u03C1', element: 'mi' },
  varrho:     { char: '\u03F1', element: 'mi' },
  sigma:      { char: '\u03C3', element: 'mi' },
  varsigma:   { char: '\u03C2', element: 'mi' },
  tau:        { char: '\u03C4', element: 'mi' },
  upsilon:    { char: '\u03C5', element: 'mi' },
  phi:        { char: '\u03D5', element: 'mi' },
  varphi:     { char: '\u03C6', element: 'mi' },
  chi:        { char: '\u03C7', element: 'mi' },
  psi:        { char: '\u03C8', element: 'mi' },
  omega:      { char: '\u03C9', element: 'mi' },

  // Greek uppercase
  Gamma:      { char: '\u0393', element: 'mi' },
  Delta:      { char: '\u0394', element: 'mi' },
  Theta:      { char: '\u0398', element: 'mi' },
  Lambda:     { char: '\u039B', element: 'mi' },
  Xi:         { char: '\u039E', element: 'mi' },
  Pi:         { char: '\u03A0', element: 'mi' },
  Sigma:      { char: '\u03A3', element: 'mi' },
  Upsilon:    { char: '\u03A5', element: 'mi' },
  Phi:        { char: '\u03A6', element: 'mi' },
  Psi:        { char: '\u03A8', element: 'mi' },
  Omega:      { char: '\u03A9', element: 'mi' },

  // Binary operators
  times:        { char: '\u00D7', element: 'mo' },
  div:          { char: '\u00F7', element: 'mo' },
  cdot:         { char: '\u22C5', element: 'mo' },
  ast:          { char: '\u2217', element: 'mo' },
  star:         { char: '\u22C6', element: 'mo' },
  circ:         { char: '\u2218', element: 'mo' },
  bullet:       { char: '\u2219', element: 'mo' },
  pm:           { char: '\u00B1', element: 'mo' },
  mp:           { char: '\u2213', element: 'mo' },
  cap:          { char: '\u2229', element: 'mo' },
  cup:          { char: '\u222A', element: 'mo' },
  vee:          { char: '\u2228', element: 'mo' },
  lor:          { char: '\u2228', element: 'mo' },
  wedge:        { char: '\u2227', element: 'mo' },
  land:         { char: '\u2227', element: 'mo' },
  oplus:        { char: '\u2295', element: 'mo' },
  ominus:       { char: '\u2296', element: 'mo' },
  otimes:       { char: '\u2297', element: 'mo' },
  oslash:       { char: '\u2298', element: 'mo' },
  odot:         { char: '\u2299', element: 'mo' },
  setminus:     { char: '\u2216', element: 'mo' },
  dagger:       { char: '\u2020', element: 'mo' },
  ddagger:      { char: '\u2021', element: 'mo' },
  amalg:        { char: '\u2A3F', element: 'mo' },
  wr:           { char: '\u2240', element: 'mo' },
  triangleleft: { char: '\u25C3', element: 'mo' },
  triangleright:{ char: '\u25B9', element: 'mo' },

  // Relations
  leq:        { char: '\u2264', element: 'mo' },
  le:         { char: '\u2264', element: 'mo' },
  geq:        { char: '\u2265', element: 'mo' },
  ge:         { char: '\u2265', element: 'mo' },
  neq:        { char: '\u2260', element: 'mo' },
  ne:         { char: '\u2260', element: 'mo' },
  approx:     { char: '\u2248', element: 'mo' },
  equiv:      { char: '\u2261', element: 'mo' },
  sim:        { char: '\u223C', element: 'mo' },
  simeq:      { char: '\u2243', element: 'mo' },
  cong:       { char: '\u2245', element: 'mo' },
  propto:     { char: '\u221D', element: 'mo' },
  prec:       { char: '\u227A', element: 'mo' },
  succ:       { char: '\u227B', element: 'mo' },
  preceq:     { char: '\u2AAF', element: 'mo' },
  succeq:     { char: '\u2AB0', element: 'mo' },
  subset:     { char: '\u2282', element: 'mo' },
  supset:     { char: '\u2283', element: 'mo' },
  subseteq:   { char: '\u2286', element: 'mo' },
  supseteq:   { char: '\u2287', element: 'mo' },
  sqsubseteq: { char: '\u2291', element: 'mo' },
  sqsupseteq: { char: '\u2292', element: 'mo' },
  in:         { char: '\u2208', element: 'mo' },
  notin:      { char: '\u2209', element: 'mo' },
  ni:         { char: '\u220B', element: 'mo' },
  mid:        { char: '\u2223', element: 'mo' },
  nmid:       { char: '\u2224', element: 'mo' },
  parallel:   { char: '\u2225', element: 'mo' },
  perp:       { char: '\u22A5', element: 'mo' },
  vdash:      { char: '\u22A2', element: 'mo' },
  dashv:      { char: '\u22A3', element: 'mo' },
  models:     { char: '\u22A8', element: 'mo' },
  ll:         { char: '\u226A', element: 'mo' },
  gg:         { char: '\u226B', element: 'mo' },
  coloneqq:   { char: '\u2254', element: 'mo' },

  // Arrows
  rightarrow:       { char: '\u2192', element: 'mo' },
  to:               { char: '\u2192', element: 'mo' },
  leftarrow:        { char: '\u2190', element: 'mo' },
  gets:             { char: '\u2190', element: 'mo' },
  leftrightarrow:   { char: '\u2194', element: 'mo' },
  Rightarrow:       { char: '\u21D2', element: 'mo' },
  implies:          { char: '\u21D2', element: 'mo' },
  Leftarrow:        { char: '\u21D0', element: 'mo' },
  impliedby:        { char: '\u21D0', element: 'mo' },
  Leftrightarrow:   { char: '\u21D4', element: 'mo' },
  iff:              { char: '\u21D4', element: 'mo' },
  uparrow:          { char: '\u2191', element: 'mo' },
  downarrow:        { char: '\u2193', element: 'mo' },
  updownarrow:      { char: '\u2195', element: 'mo' },
  Uparrow:          { char: '\u21D1', element: 'mo' },
  Downarrow:        { char: '\u21D3', element: 'mo' },
  Updownarrow:      { char: '\u21D5', element: 'mo' },
  mapsto:           { char: '\u21A6', element: 'mo' },
  hookrightarrow:   { char: '\u21AA', element: 'mo' },
  hookleftarrow:    { char: '\u21A9', element: 'mo' },
  nearrow:          { char: '\u2197', element: 'mo' },
  searrow:          { char: '\u2198', element: 'mo' },
  nwarrow:          { char: '\u2196', element: 'mo' },
  swarrow:          { char: '\u2199', element: 'mo' },
  rightharpoonup:   { char: '\u21C0', element: 'mo' },
  rightharpoondown: { char: '\u21C1', element: 'mo' },
  leftharpoonup:    { char: '\u21BC', element: 'mo' },
  leftharpoondown:  { char: '\u21BD', element: 'mo' },
  longrightarrow:   { char: '\u27F6', element: 'mo' },
  longleftarrow:    { char: '\u27F5', element: 'mo' },
  longleftrightarrow: { char: '\u27F7', element: 'mo' },
  Longrightarrow:   { char: '\u27F9', element: 'mo' },
  Longleftarrow:    { char: '\u27F8', element: 'mo' },
  Longleftrightarrow: { char: '\u27FA', element: 'mo' },
  longmapsto:       { char: '\u27FC', element: 'mo' },

  // Big operators
  sum:      { char: '\u2211', element: 'mo' },
  prod:     { char: '\u220F', element: 'mo' },
  coprod:   { char: '\u2210', element: 'mo' },
  int:      { char: '\u222B', element: 'mo' },
  iint:     { char: '\u222C', element: 'mo' },
  iiint:    { char: '\u222D', element: 'mo' },
  oint:     { char: '\u222E', element: 'mo' },
  bigcup:   { char: '\u22C3', element: 'mo' },
  bigcap:   { char: '\u22C2', element: 'mo' },
  bigvee:   { char: '\u22C1', element: 'mo' },
  bigwedge: { char: '\u22C0', element: 'mo' },
  bigoplus: { char: '\u2A01', element: 'mo' },
  bigotimes:{ char: '\u2A02', element: 'mo' },
  bigsqcup: { char: '\u2A06', element: 'mo' },
  biguplus: { char: '\u2A04', element: 'mo' },
  bigodot:  { char: '\u2A00', element: 'mo' },

  // Miscellaneous symbols
  infty:    { char: '\u221E', element: 'mi' },
  partial:  { char: '\u2202', element: 'mo' },
  nabla:    { char: '\u2207', element: 'mo' },
  forall:   { char: '\u2200', element: 'mo' },
  exists:   { char: '\u2203', element: 'mo' },
  nexists:  { char: '\u2204', element: 'mo' },
  neg:      { char: '\u00AC', element: 'mo' },
  lnot:     { char: '\u00AC', element: 'mo' },
  emptyset: { char: '\u2205', element: 'mi' },
  varnothing: { char: '\u2205', element: 'mi' },
  ell:      { char: '\u2113', element: 'mi' },
  wp:       { char: '\u2118', element: 'mi' },
  Re:       { char: '\u211C', element: 'mi' },
  Im:       { char: '\u2111', element: 'mi' },
  aleph:    { char: '\u2135', element: 'mi' },
  hbar:     { char: '\u210F', element: 'mi' },
  imath:    { char: '\u0131', element: 'mi' },
  jmath:    { char: '\u0237', element: 'mi' },
  prime:    { char: '\u2032', element: 'mo' },
  angle:    { char: '\u2220', element: 'mo' },
  triangle: { char: '\u25B3', element: 'mo' },
  top:      { char: '\u22A4', element: 'mo' },
  bot:      { char: '\u22A5', element: 'mo' },
  flat:     { char: '\u266D', element: 'mo' },
  natural:  { char: '\u266E', element: 'mo' },
  sharp:    { char: '\u266F', element: 'mo' },
  clubsuit: { char: '\u2663', element: 'mi' },
  diamondsuit: { char: '\u2662', element: 'mi' },
  heartsuit:   { char: '\u2661', element: 'mi' },
  spadesuit:   { char: '\u2660', element: 'mi' },
  surd:     { char: '\u221A', element: 'mo' },
  checkmark:{ char: '\u2713', element: 'mo' },
  complement: { char: '\u2201', element: 'mo' },

  // Additional symbols
  backslash:  { char: '\\',     element: 'mo' },
  lmoustache: { char: '\u23B0', element: 'mo' },
  rmoustache: { char: '\u23B1', element: 'mo' },
  lgroup:     { char: '\u27EE', element: 'mo' },
  rgroup:     { char: '\u27EF', element: 'mo' },
  lbrack:     { char: '[',      element: 'mo' },
  rbrack:     { char: ']',      element: 'mo' },
  Vert:       { char: '\u2016', element: 'mo' },
  lt:         { char: '<',      element: 'mo' },
  gt:         { char: '>',      element: 'mo' },

  // AMS binary operators
  boxplus:          { char: '\u229E', element: 'mo' },
  boxminus:         { char: '\u229F', element: 'mo' },
  boxtimes:         { char: '\u22A0', element: 'mo' },
  boxdot:           { char: '\u22A1', element: 'mo' },
  intercal:         { char: '\u22BA', element: 'mo' },
  veebar:           { char: '\u22BB', element: 'mo' },
  barwedge:         { char: '\u22BC', element: 'mo' },
  doublebarwedge:   { char: '\u2A5E', element: 'mo' },
  curlywedge:       { char: '\u22CF', element: 'mo' },
  curlyvee:         { char: '\u22CE', element: 'mo' },
  ltimes:           { char: '\u22C9', element: 'mo' },
  rtimes:           { char: '\u22CA', element: 'mo' },
  leftthreetimes:   { char: '\u22CB', element: 'mo' },
  rightthreetimes:  { char: '\u22CC', element: 'mo' },
  circleddash:      { char: '\u229D', element: 'mo' },
  circledast:       { char: '\u229B', element: 'mo' },
  circledcirc:      { char: '\u229A', element: 'mo' },
  centerdot:        { char: '\u22C5', element: 'mo' },
  divideontimes:    { char: '\u22C7', element: 'mo' },
  dotplus:          { char: '\u2214', element: 'mo' },
  Cap:              { char: '\u22D2', element: 'mo' },
  Cup:              { char: '\u22D3', element: 'mo' },
  doublecap:        { char: '\u22D2', element: 'mo' },
  doublecup:        { char: '\u22D3', element: 'mo' },

  // AMS relations
  lll:              { char: '\u22D8', element: 'mo' },
  ggg:              { char: '\u22D9', element: 'mo' },
  lessgtr:          { char: '\u2276', element: 'mo' },
  gtrless:          { char: '\u2277', element: 'mo' },
  trianglelefteq:   { char: '\u22B4', element: 'mo' },
  trianglerighteq:  { char: '\u22B5', element: 'mo' },
  vartriangleleft:  { char: '\u22B2', element: 'mo' },
  vartriangleright: { char: '\u22B3', element: 'mo' },
  between:          { char: '\u226C', element: 'mo' },
  pitchfork:        { char: '\u22D4', element: 'mo' },
  backepsilon:      { char: '\u03F6', element: 'mo' },
  smallsmile:       { char: '\u2323', element: 'mo' },
  smallfrown:       { char: '\u2322', element: 'mo' },
  smile:            { char: '\u2323', element: 'mo' },
  frown:            { char: '\u2322', element: 'mo' },
  Subset:           { char: '\u22D0', element: 'mo' },
  Supset:           { char: '\u22D1', element: 'mo' },
  sqsubset:         { char: '\u228F', element: 'mo' },
  sqsupset:         { char: '\u2290', element: 'mo' },
  bumpeq:           { char: '\u224F', element: 'mo' },
  Bumpeq:           { char: '\u224E', element: 'mo' },
  doteq:            { char: '\u2250', element: 'mo' },
  doteqdot:         { char: '\u2251', element: 'mo' },
  fallingdotseq:    { char: '\u2252', element: 'mo' },
  risingdotseq:     { char: '\u2253', element: 'mo' },
  eqcirc:           { char: '\u2256', element: 'mo' },
  circeq:           { char: '\u2257', element: 'mo' },
  triangleq:        { char: '\u225C', element: 'mo' },
  thicksim:         { char: '\u223C', element: 'mo' },
  thickapprox:      { char: '\u2248', element: 'mo' },
  backsim:          { char: '\u223D', element: 'mo' },
  backsimeq:        { char: '\u22CD', element: 'mo' },
  vDash:            { char: '\u22A8', element: 'mo' },
  Vdash:            { char: '\u22A9', element: 'mo' },
  Vvdash:           { char: '\u22AA', element: 'mo' },

  // AMS negated relations
  nleq:             { char: '\u2270', element: 'mo' },
  ngeq:             { char: '\u2271', element: 'mo' },
  nless:            { char: '\u226E', element: 'mo' },
  ngtr:             { char: '\u226F', element: 'mo' },
  nprec:            { char: '\u2280', element: 'mo' },
  nsucc:            { char: '\u2281', element: 'mo' },
  subsetneq:        { char: '\u228A', element: 'mo' },
  supsetneq:        { char: '\u228B', element: 'mo' },
  varsubsetneq:     { char: '\u228A\uFE00', element: 'mo' },
  varsupsetneq:     { char: '\u228B\uFE00', element: 'mo' },
  nsubseteq:        { char: '\u2288', element: 'mo' },
  nsupseteq:        { char: '\u2289', element: 'mo' },
  ntriangleleft:    { char: '\u22EA', element: 'mo' },
  ntriangleright:   { char: '\u22EB', element: 'mo' },
  ntrianglelefteq:  { char: '\u22EC', element: 'mo' },
  ntrianglerighteq: { char: '\u22ED', element: 'mo' },

  // AMS arrows
  twoheadrightarrow:  { char: '\u21A0', element: 'mo' },
  twoheadleftarrow:   { char: '\u219E', element: 'mo' },
  rightarrowtail:     { char: '\u21A3', element: 'mo' },
  leftarrowtail:      { char: '\u21A2', element: 'mo' },
  rightrightarrows:   { char: '\u21C9', element: 'mo' },
  leftleftarrows:     { char: '\u21C7', element: 'mo' },
  rightleftarrows:    { char: '\u21C4', element: 'mo' },
  leftrightarrows:    { char: '\u21C6', element: 'mo' },
  Rsh:                { char: '\u21B1', element: 'mo' },
  Lsh:                { char: '\u21B0', element: 'mo' },
  circlearrowleft:    { char: '\u21BA', element: 'mo' },
  circlearrowright:   { char: '\u21BB', element: 'mo' },
  curvearrowleft:     { char: '\u21B6', element: 'mo' },
  curvearrowright:    { char: '\u21B7', element: 'mo' },
  multimap:           { char: '\u22B8', element: 'mo' },
  upuparrows:         { char: '\u21C8', element: 'mo' },
  downdownarrows:     { char: '\u21CA', element: 'mo' },
  restriction:        { char: '\u21BE', element: 'mo' },
  upharpoonright:     { char: '\u21BE', element: 'mo' },
  upharpoonleft:      { char: '\u21BF', element: 'mo' },
  downharpoonright:   { char: '\u21C2', element: 'mo' },
  downharpoonleft:    { char: '\u21C3', element: 'mo' },
  rightleftharpoons:  { char: '\u21CC', element: 'mo' },
  leftrightharpoons:  { char: '\u21CB', element: 'mo' },

  // AMS symbols
  eth:                { char: '\u00F0', element: 'mi' },
  mho:                { char: '\u2127', element: 'mi' },
  Finv:               { char: '\u2132', element: 'mi' },
  Game:               { char: '\u2141', element: 'mi' },
  digamma:            { char: '\u03DD', element: 'mi' },
  varkappa:           { char: '\u03F0', element: 'mi' },
  hslash:             { char: '\u210F', element: 'mi' },
  Bbbk:               { char: '\uD835\uDD5C', element: 'mi' },
  circledS:           { char: '\u24C8', element: 'mo' },
  circledR:           { char: '\u00AE', element: 'mo' },
  lozenge:            { char: '\u25CA', element: 'mo' },
  blacklozenge:       { char: '\u29EB', element: 'mo' },
  blacktriangle:      { char: '\u25B4', element: 'mo' },
  blacktriangledown:  { char: '\u25BE', element: 'mo' },
  blacksquare:        { char: '\u25A0', element: 'mo' },
  square:             { char: '\u25A1', element: 'mo' },
  bigstar:            { char: '\u2605', element: 'mo' },
  sphericalangle:     { char: '\u2222', element: 'mo' },
  measuredangle:      { char: '\u2221', element: 'mo' },
  diagup:             { char: '\u2571', element: 'mo' },
  diagdown:           { char: '\u2572', element: 'mo' },
  maltese:            { char: '\u2720', element: 'mo' },

  // Additional integrals
  smallint:           { char: '\u222B', element: 'mo' },
  iiiint:             { char: '\u2A0C', element: 'mo' },
  idotsint:           { char: '\u222B\u22EF\u222B', element: 'mo' },

  // Logo-like
  KaTeX:              { char: 'KaTeX', element: 'mi' },
  LaTeX:              { char: 'LaTeX', element: 'mi' },
  TeX:                { char: 'TeX', element: 'mi' },

  // Dots
  ldots:  { char: '\u2026', element: 'mo' },
  cdots:  { char: '\u22EF', element: 'mo' },
  vdots:  { char: '\u22EE', element: 'mo' },
  ddots:  { char: '\u22F1', element: 'mo' },
  dots:   { char: '\u2026', element: 'mo' },

  // Delimiter symbols (when not used with \left/\right)
  langle:   { char: '\u27E8', element: 'mo' },
  rangle:   { char: '\u27E9', element: 'mo' },
  lfloor:   { char: '\u230A', element: 'mo' },
  rfloor:   { char: '\u230B', element: 'mo' },
  lceil:     { char: '\u2308', element: 'mo' },
  rceil:     { char: '\u2309', element: 'mo' },
  lbrace:   { char: '{', element: 'mo' },
  rbrace:   { char: '}', element: 'mo' },
  lvert:    { char: '|', element: 'mo' },
  rvert:    { char: '|', element: 'mo' },
  lVert:    { char: '\u2016', element: 'mo' },
  rVert:    { char: '\u2016', element: 'mo' },
};

/** Accent command definitions. */
export interface AccentDef {
  /** Unicode combining character */
  char: string;
  /** Whether the accent goes over (true) or under (false) the base */
  over: boolean;
}

export const accents: Record<string, AccentDef> = {
  hat:        { char: '\u0302', over: true },
  widehat:    { char: '\u0302', over: true },
  tilde:      { char: '\u0303', over: true },
  widetilde:  { char: '\u0303', over: true },
  bar:        { char: '\u0304', over: true },
  overline:   { char: '\u0305', over: true },
  vec:        { char: '\u20D7', over: true },
  overrightarrow: { char: '\u2192', over: true },
  overleftarrow:  { char: '\u2190', over: true },
  dot:        { char: '\u02D9', over: true },
  ddot:       { char: '\u00A8', over: true },
  dddot:      { char: '\u20DB', over: true },
  breve:      { char: '\u02D8', over: true },
  check:      { char: '\u02C7', over: true },
  acute:      { char: '\u00B4', over: true },
  grave:      { char: '\u0060', over: true },
  mathring:   { char: '\u02DA', over: true },
  underline:  { char: '\u0332', over: false },
  underbrace: { char: '\u23DF', over: false },
  overbrace:  { char: '\u23DE', over: true },
  overparen:  { char: '\u23DC', over: true },
  underparen: { char: '\u23DD', over: false },
  overbracket: { char: '\u23B4', over: true },
  underbracket: { char: '\u23B5', over: false },
};

/** Whether an accent should be stretchy. */
export const wideAccents = new Set([
  'widehat', 'widetilde', 'overline', 'overrightarrow', 'overleftarrow',
  'underline', 'underbrace', 'overbrace',
  'overparen', 'underparen', 'overbracket', 'underbracket',
]);

/** Over/under decorations that are not true accents (no accent/accentunder attr). */
export const nonAccentDecorations = new Set([
  'overbrace', 'underbrace', 'overparen', 'underparen',
  'overbracket', 'underbracket',
]);

/** Named math operators (upright, no limits by default). */
export const operatorNames = new Set([
  'arccos', 'arcsin', 'arctan', 'arg', 'cos', 'cosh', 'cot', 'coth',
  'csc', 'deg', 'dim', 'exp', 'hom', 'ker', 'lg', 'ln', 'log',
  'sec', 'sin', 'sinh', 'tan', 'tanh',
]);

/** Named math operators with movable limits (display mode: over/under). */
export const operatorNamesWithLimits = new Set([
  'det', 'gcd', 'inf', 'lim', 'liminf', 'limsup', 'max', 'min',
  'Pr', 'sup',
]);

/** Big operators that take limits. */
export const bigOperators = new Set([
  'sum', 'prod', 'coprod', 'bigcup', 'bigcap', 'bigvee', 'bigwedge',
  'bigoplus', 'bigotimes', 'bigsqcup', 'biguplus', 'bigodot',
  'iiiint', 'idotsint',
]);

/** Delimiter command → Unicode mapping (for \left/\right). */
export const delimiters: Record<string, string> = {
  '(': '(',
  ')': ')',
  '[': '[',
  ']': ']',
  '{': '{',
  '}': '}',
  '|': '|',
  '\\|': '\u2016',
  '.': '',   // invisible delimiter
  '/': '/',
  '\\': '\\',
  langle: '\u27E8',
  rangle: '\u27E9',
  lfloor: '\u230A',
  rfloor: '\u230B',
  lceil: '\u2308',
  rceil: '\u2309',
  lbrace: '{',
  rbrace: '}',
  lvert: '|',
  rvert: '|',
  lVert: '\u2016',
  rVert: '\u2016',
  uparrow: '\u2191',
  downarrow: '\u2193',
  updownarrow: '\u2195',
  Uparrow: '\u21D1',
  Downarrow: '\u21D3',
  Updownarrow: '\u21D5',
  // Aliases
  lbrack: '[',
  rbrack: ']',
  lt: '\u27E8',
  gt: '\u27E9',
  backslash: '\\',
  // Moustache and group delimiters
  lmoustache: '\u23B0',
  rmoustache: '\u23B1',
  lgroup: '\u27EE',
  rgroup: '\u27EF',
  arrowvert: '|',
  Arrowvert: '\u2016',
  bracevert: '|',
  Vert: '\u2016',
};

/** mathvariant values for \mathXX commands. */
export const fontCommands: Record<string, string> = {
  mathrm: 'normal',
  mathbf: 'bold',
  mathit: 'italic',
  mathsf: 'sans-serif',
  mathtt: 'monospace',
  mathbb: 'double-struck',
  mathcal: 'script',
  mathscr: 'script',
  mathfrak: 'fraktur',
};
